### ISSUE TITLE
tinkers hamer with fortune 3

### ISSUE THREAD

**Issue by lalleman44** [AllTheMods/ATM-3#264] opened 2017-11-10 09:16 UTC
The tinkers hamer makes the game crash  :(
[crash-2017-11-10_10.13.43-client.txt](https://github.com/AllTheMods/ATM-3/files/1460762/crash-2017-11-10_10.13.43-client.txt)

**Comment by OrdinatorStouff** [comment] 2017-11-10 17:48
Duplicate of #99 

You can't "look" at mechanism pipes while holding a tinker's hammer or game will crash. To be able to log back in you need to edit your player data; move the location to somewhere else or change the actively selected slot to some other item etc.

**Closed by OrdinatorStouff** 2017-11-10 17:48 UTC
Labels: bug, duplicate, mod issue

**Comment by lalleman44** [comment] 2017-11-10 21:35
oke , great bug :D i can play for a little while, but it indeed crashes when i use the hammer in the neighborhood of the pipes :S thanks for the info :)
