### ISSUE TITLE
Tin Ingots, and anothers.

### ISSUE THREAD

**Issue by Alitabear** [AllTheMods/ATM-3#886] opened 2019-06-28 16:17 UTC
So all the ingots i make with Mekanism seem to have next to no way to make thermal ingots? It wont even let me make Mekanism blocks from the ingots. I'm just so confused. Also random stacks of different kinds of tin is kinda annoying. :( 

## Expected Behavior
Tin ingots be made into blocks, used in all tin ingot recipes.

## Current Behavior
mekanism tin and thermal tin are not the same and don't always share the same recipes.

## Possible Solution
Oredict them? I'm not sure how that works but im assuming theres a way to make all recipes use/output the same kind of tin ingot. 

## Steps to Reproduce
1. Use mekanism to make ingots
2. try to make thermal things
3. Doesnt work. Am sad.

## Log
Not needed? i think..

## Detailed Description
Oredict all the ingots? So i dont have random stakcs of different ingots and things. Please! <3

**Comment by FallenEagle1** [comment] 2019-06-28 16:34
Duplicate of #861 and is being looked into.

**Closed by FallenEagle1** 2019-06-28 16:34 UTC
