### ISSUE TITLE
Cannot get "quantum entangled singularity" even with terraqueous ender dust

### ISSUE THREAD

**Issue by huang-junwei** [AllTheMods/ATM-3#724] opened 2018-08-18 03:12 UTC
## Expected Behavior

putting an ender dust from AE2 and a singularity together on the ground near an explosion should yield 2 quantum entangled singularity

## Current Behavior

none of the available ender dust, including previously suggested "terraqueous ender dust", in the pack gives a quantum entangled singularity when putting them and a singularity together on the ground near an explosion

## Possible Solution

Same suggestion as before, AE2 seems to only check their own ender dust when attempting to create the quantum entangled singularity. However, the AE2 ender dust seems to be disabled in this pack and I think allowing some way to craft AE2 ender dust will be able to help

## Steps to Reproduce

1.
2.
3.
4.

**Comment by martmists** [comment] 2018-08-18 07:56
Duplicate of #717, please reopen that instead of making a new issue.

**Closed by martmists** 2018-08-18 07:56 UTC
