### ISSUE TITLE
Akashic tome issues

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM-3#911] opened 2019-08-19 15:05 UTC
Patchoulli book has no texture
![image](https://user-images.githubusercontent.com/25225145/63276339-c7717680-c268-11e9-9022-ef324c8c3c74.png)

Potential issue with scripts?
https://www.reddit.com/r/allthemods/comments/cs8p2u/akashic_tome_error/

**Comment by Pelotrio** [comment] 2021-05-18 14:37
Duplicate of #975

**Closed by Pelotrio** 2021-05-18 14:37 UTC
