### ISSUE TITLE
New version (5.2) getting 0-1 fps

### ISSUE THREAD

**Issue by jlewismoss** [AllTheMods/ATM-3#299] opened 2017-11-29 01:13 UTC
I'm getting basically no frames with the newest version.  5.1 was fine.

I created a new world thinking it was something from the old save.  No change.

The world is also not loading in.  The one chunk I'm standing in loads after 20 seconds or so but it takes minutes for the next to load in.

Other than updating forge I made no changes to the configuration.

This is on a linux box where I use MultiMC to build the instance and curseDownloader to download all the packages.

**Comment by JuppSchlupp** [comment] 2017-11-29 14:35
I had the same problem. The troublemaker was that Wizardry mod. After disabling it, my Fps Jumped back to 120-130 like i had in 5.1

**Comment by coolsa** [comment] 2017-12-01 00:21
Can confirm, having the same experience on linux at this moment. I have tried several things to no avail.

The main error i am getting in game:
An issue in the root.tile.textures is the cause of the fps drops.


The things I have tried:

- Oracle JDK and JRE, as well as Open JDK and JRE.
- Java 7 and 8 (7 crashes on launch, 8 works all right until in game with no fps)
- Changing forge versions to earlier versions (down to 2555 tried so far, long restart times cause me to avoid this)
- Restarting several times with my default settings (forge 2556, jdk 1.8.0_152)
- Updating my graphics drivers
- Upgrading my linux kernal build
- Changing amounts of dedicated ram (4 gigs up to 8 gbs tried to no avail)

I am avoiding removing or disabling any mods, as I am playing on a server with some friends.

The things i have yet to try:

- Installing the server files of ATM3 and then trying to run those through several launchers
- booting off of a live installation medium and trying from there
- running a virtual machine and seeing if a mod is targeting my distro of linux.
- doing a deep read of my logs and seeing if it is due to a specific mod, or drivers missing.

I will update this with more information as i get to it.

**Comment by OrdinatorStouff** [comment] 2017-12-01 00:32
can you try disabling the Blur mod and see if that helps?

**Comment by coolsa** [comment] 2017-12-01 00:45
blur does not seem to be in the list of mods that i have, is it an option in another mod?

**Comment by OrdinatorStouff** [comment] 2017-12-01 16:18
Thanks for the followup coolsa and I'm glad it's working for you. I don't know if the same fix can help @JuppSchlupp @jlewismoss -- can either of you test and confirm?

**Comment by JuppSchlupp** [comment] 2017-12-01 18:22
Ok, i tried that. Optifine installed, running Minecraft, loaded my World, had to face 0-1 fps, hit Esc and changed the Terrain animated setting and the fps instantly got normal again.
Thnx @coolsa 
Little sitenote: Iam not running linux like coolsa or jlewismoss. Iam running Win10

**Comment by jlewismoss** [comment] 2017-12-03 15:59
Optifine worked for me as well.  I dislike optifine though because it tends to mess with the coloring and environmental effects that bop adds.

**Comment by OrdinatorStouff** [comment] 2017-12-04 20:14
Looks like we figured out a common solution. I don't know the cause/reason, however it only affects a minorty population of the modpacks users anyway. Going to close this ticket out as resolved. Thanks for the feedback and help from everyone, too.

**Closed by OrdinatorStouff** 2017-12-04 20:14 UTC
Labels: annoying, intermittent/hard to track down, wontfix
