### ISSUE TITLE
Player Randomly Getting Stuck

### ISSUE THREAD

**Issue by WillDieForPie** [AllTheMods/ATM-3#101] opened 2017-08-26 05:36 UTC
Pack version: v3.0
Forge version: 14.22.0.2456
Server: ATM3 Official Server

From time to time I will get randomly stuck and cannot move. The only way to get unstuck is to teleport somewhere ( /home or /spawn ) and then re-log. This issue has been experienced by other players, and not only me. Oddly, after re-logging a death waypoint will appear where you teleported from before re-logging, but you do not actually die and a death is not counted.

Edit: There have been a few times where me and my friend would get stuck at **exactly** the same time.

**Comment by OrdinatorStouff** [comment] 2017-09-05 04:33
dupe of #26 -- valid issue to be figured out but only need the one issue tracker for it

**Closed by OrdinatorStouff** 2017-09-05 04:33 UTC
Labels: duplicate
