### ISSUE TITLE
Crash when teleporting

### ISSUE THREAD

**Issue by TheElectricCake** [AllTheMods/ATM-3#67] opened 2017-07-20 00:49 UTC
This looks rather similar to Garlaen's problem. This problem starts for me after I teleport home or after I return from another dimension to my home chunk (whether from the End or from the Mining World). WAILA will show "waiting for server" no matter what I look at, then I'll be logged out from the server after about 20-30 seconds. Sometimes I can't log back in, the same thing just keeps happening. I log in and it logs me right back out again after the same WAILA "waiting for server" delay.

Reinstalling fixes it but then I lose all of my journeymap and bookmarks (where the hell are those stored?! Not the journeymap folder, apparently!). And I shouldn't need to keep reinstalling.

This is the ONLY modpack which this happens on. I routinely play ATM(1), Crackpack, Space Astronomy and Horizons and I don't see this problem in any of the rest of them even once, but it happens to me on ATM3 about once every day or two!

It just happened again, today and I grabbed the log file. It's at https://pastebin.com/tQHYx86D

**Comment by OrdinatorStouff** [comment] 2017-09-04 23:48
closing as duplicate of #75

**Closed by OrdinatorStouff** 2017-09-04 23:48 UTC
Labels: duplicate, intermittent/hard to track down
