### ISSUE TITLE
ProjectRed Copper Ingot Not Compatible With All Recipes That Require Copper

### ISSUE THREAD

**Issue by Aternias** [AllTheMods/ATM-3#921] opened 2019-09-06 22:03 UTC
When trying to use copper from ProjectRed (not Thermal Foundation), it doesn't recognize it as a compatible copper that can be used in recipes. You get the ProjectRed ingots instead of the Thermal Foundation ones by using a smeltery, making it into a block and breaking it into 9 ingots. But cooling them into ingots gives you the Thermal Foundation ones instead.

## Expected Behavior
The Copper Ingots from ProjectRed should be usable in all recipes that require copper, or they should be replaced altogether with the Thermal Expansion copper and be disabled altogether.

## Current Behavior
Making a Copper Gear using the projected copper does not work. This may also be an issue with other recipes but I have not come across them yet.

## Possible Solution
Having many different copper ingots from separate mods is confusing, they don't stack, and they don't always work.

## Steps to Reproduce
1. Melt Copper In A Tinkers' Construct Smeltery.
2. Mold The Copper Into A Block.
3. Break The Block Into 9 Ingots. (They Should Turn Into ProjectRed Copper Ingots)
4. Try Making A Copper Gear, It Shouldn't Be Working.

## Detailed Description
Any ingots with the same name from different mods should be consolidated into one ingot from one mod, so rather than there being 3 different coppers, just use the copper ingot from Thermal Expansion. I know OreDict is a thing, but it's still confusing, you can't stack identical ingots from different mods and it takes up more inventory space.

**Comment by FallenEagle1** [comment] 2019-09-06 23:45
Duplicate of #861

**Closed by FallenEagle1** 2019-09-06 23:45 UTC
