### ISSUE TITLE
Duplicate Types of the Same Ore Generating

### ISSUE THREAD

**Issue by Sirius902** [AllTheMods/ATM-3#634] opened 2018-06-20 19:25 UTC
The title is pretty self explanatory, but specifically copper, lead, silver, and tin ores are generating from both Thermal Foundation and Tech Reborn.

## Expected Behavior
I would expect only one mod's version of an ore to spawn as mining can get very tedious having duplicate ores taking up all your inventory space and can cause too much ore of a certain type to generate if both mods are trying to generate it.

## Possible Solution
A way to fix this would be to change the ores.json config file for Tech Reborn under teamreborn/techreborn/ and change the boolean value for shouldSpawn for the offending ores to false instead of true to prevent them from spawning.

## Steps to Reproduce
1. Generate a new world with cheats enabled.
2. Type the "/oredistribution 32 0 64" command into the chat.
3. You will see that it warns of multiple variants of the same ore for copper, lead, silver, and tin.

**Comment by Yoosk** [comment] 2018-06-20 19:27
duplicate of https://github.com/AllTheMods/ATM-3/issues/623.

**Closed by Yoosk** 2018-06-20 19:27 UTC
Labels: duplicate

**Comment by Sirius902** [comment] 2018-06-20 19:54
Oops sorry didn't think to look in the closed section to see if it was a duplicate.
