### ISSUE TITLE
Tin and Copper Ore. ProjectRed

### ISSUE THREAD

**Issue by fxceptioN** [AllTheMods/ATM-3#914] opened 2019-08-21 21:03 UTC
Put Copper ore in the smeltery and made some blocks, when putting the block into a crafting grid to turn it into ingots, it turns those ingots into projectred ingots. It does the same thing with tin.

Expected Behavior
should be turning it into thermal foundation ingots

**Comment by martmists** [comment] 2019-08-23 09:33
Is there an issue here? Projectred ingots should work fine in oredicted recipes.

**Comment by FallenEagle1** [comment] 2019-08-23 12:33
Except they don't for some reason. Duplicate of #861

**Closed** 2019-08-23 12:34 UTC
