### ISSUE TITLE
EnderIO causing crash

### ISSUE THREAD

**Issue by sonvar** [AllTheMods/ATM-3#610] opened 2018-06-01 14:05 UTC
## Expected Behavior

Using an EnderIO Yeta wrench on an EnderIO capacitor bank  to toggle on the in/out display screen. 

## Current Behavior

When doing so, game crashes.

## Possible Solution

Unknown

## Steps to Reproduce

1. Have a basic capacitor bank in world.
2. Shift left click it with a yeta wrench.
3. game crashes/
 
Repeated this 3 times to verify that it was the yeta wrench/basic capacitor interaction that causes the crash.

## Log

https://github.com/sonvar/crash-report/blob/master/crash-2018-06-01_22.38.07-client.txt

## Detailed Description

Unknown

**Comment by Yoosk** [comment] 2018-06-01 14:13
I really hate you. Known issue and
Duplicate of https://github.com/AllTheMods/ATM-3/issues/578, https://github.com/AllTheMods/ATM-3/issues/586, https://github.com/AllTheMods/ATM-3/issues/565.

**Comment by Boomflex** [comment] 2018-06-01 14:53
Please check closed Issues.

Closed.

**Closed by Boomflex** 2018-06-01 14:53 UTC
