### ISSUE TITLE
Chunk Loading

### ISSUE THREAD

**Issue by Lyriox** [AllTheMods/ATM-3#310] opened 2017-12-05 19:55 UTC
After quiting from a World and reloging into it does remove Chunkloading from Claimed Chunks by FTBUtilities (4.2.3) im playing on the latest ATM3 Version

**Comment by OrdinatorStouff** [comment] 2017-12-27 22:16
closing as duplicate of https://github.com/AllTheMods/ATM-3/issues/306 -- will track discussion there

**Closed by OrdinatorStouff** 2017-12-27 22:16 UTC
Labels: duplicate
