### ISSUE TITLE
Crash when attemping to autofill recipe for Mekanism advanced solar.

### ISSUE THREAD

**Issue by ConnCraft** [AllTheMods/ATM-3#343] opened 2017-12-26 19:35 UTC
https://pastebin.com/sG0t6YUq

**Comment by OrdinatorStouff** [comment] 2017-12-27 21:12
Duplicate of https://github.com/AllTheMods/ATM-3/issues/253 and https://github.com/AllTheMods/ATM-3/issues/295

Known mod conflict from Mek and TiCo crafting bench. The mod devs have tried to fix it but can't and we have no control over it at the pack level either.

you can log in avoiding the crash by changing the tinker's construct "render items in game" setting to at least remove the ingredients from the crafting table.

To craft Mek items, use anything other than a TiCo bench.

**Closed by OrdinatorStouff** 2017-12-27 21:12 UTC
Labels: duplicate, mod issue
