### ISSUE TITLE
Mekanism universal cables causes error, kicked from session

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-3#314] opened 2017-12-08 19:20 UTC
Whenever you try to use the Configurator on Mekanism cables, you get kicked from the game because of a fatal error. [This should be the error I think?](https://pastebin.com/gVWBA5LD)

**Comment by OrdinatorStouff** [comment] 2017-12-08 20:41
Duplicate of https://github.com/AllTheMods/ATM-3/issues/305
It's fixed in Mek's code but we're waiting for it to go on curse before we're allowed to include it in the modpack

**Closed by OrdinatorStouff** 2017-12-08 20:41 UTC
Labels: duplicate, mod issue
