### ISSUE TITLE
rftools 6.0 dimension removal bug

### ISSUE THREAD

**Issue by GrimZero** [AllTheMods/ATM-3#718] opened 2018-08-16 13:30 UTC
## Expected Behavior
Removing the dimension with TNT in the dimension editor should remove the dimension and allow for the creation of new ones.

## Current Behavior

Dimension inscriber shows "Too many dimensions" message. And it doesn't accept the realised tablet to power the dimension. (Checking the data in commands told me the dimensions weren't there but I couldn't create more)

## Possible Solution

Possibly check the location where the dimension amount is saved and make sure it updates.

## Steps to Reproduce

1. Create the maximum allowed dimension amount set by the config of rftdim
2. Delete the dimensions using TNT in the Editor
3. Make another dimension and power it (In my case this didnt work)

**Comment by FallenEagle1** [comment] 2018-08-19 21:58
I'm not able to reproduce this in the 6.0 test pack. I made a number of dimensions until I hit the max in config (2 in this case) tried making a third and had it say too many dimensions. Pulled the third out of the builder, destroyed one of the previous two, and was then able to put the third into the builder and make it.

**Comment by FallenEagle1** [comment] 2018-08-19 23:37
Maybe an older version. In any case, the rftools mod was updated for 6.0, so main thing will be to see if the issue shows up then as well. Going to close this for now, but if you find that this bug persists in some fashion reopen this, or if its on the 6.0 update open a new issue on it, so it can be gotten to the bottom of the issue.

**Closed by FallenEagle1** 2018-08-19 23:37 UTC
