### ISSUE TITLE
Null Pointer Exception - Mekanism interaction?

### ISSUE THREAD

**Issue by zeklaine** [AllTheMods/ATM-3#99] opened 2017-08-24 13:34 UTC
I get this null pointer frequently when my mekanism machines are running and I'm standing nearby.

https://pastebin.com/txVxPXB9

Unreported exception thrown!
java.lang.NullPointerException
    at mekanism.common.block.BlockTransmitter.func_180640_a(BlockTransmitter.java:178)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185918_c(BlockStateContainer.java:432)
    at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2767)
    at slimeknights.tconstruct.tools.common.client.RenderEvents.renderExtraBlockBreak(RenderEvents.java:78)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1673_RenderEvents_renderExtraBlockBreak_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:160)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at Reflector.callVoid(Reflector.java:549)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1912)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1361)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by OrdinatorStouff** [comment] 2017-09-05 04:23
Supposedly this has been fixed in recent mekanism releases per [this ](https://github.com/aidancbrady/Mekanism/issues/4487#issuecomment-320487662)-- but I'm not 100% convinced. I'll close this issue for now but if more continue to come up in recent 3.1+ pack versions then we'll have to follow-back up with the mod devs

**Closed by OrdinatorStouff** 2017-09-05 04:23 UTC

**Comment by RJ-Fynydd** [comment] 2017-09-10 22:57
Yeah this issue seems to be happening to a few players on our server as well.

**Comment by PotatoSauceVFX** [comment] 2017-09-10 22:57
Yeah this issue seems to be happening to a few players on our server as well.

**Comment by thiakil** [comment] 2017-09-17 08:11
This should be fixed for good in the next builds. In the meantime don't look at a Mekanism pipe/cable/tube with a Tinkers tool equipped

**Comment by DDzwiedziu** [comment] 2017-10-02 19:33
I need to dispute the ticket's closing. This [1] crash occurred when the player was looking at a universal cable [2] with a TC's hammer in hand.
This was confirmed by removing every Mekanism cable and machine in the vicinity and letting the player log in, successfully this time. 

ATM3 4.0

[1] https://pastebin.com/r2NJZ5iv
[2] Connected to a LV connector and IC2 Macerator

**Comment by OrdinatorStouff** [comment] 2017-10-02 21:32
The fix has been applied to Mekanism codebase but the mod has not had a release build uploaded to curse in almost a month. We can't distribute custom builds through curse so we're at the mercy of Mekanism's update schedule for a version with the fix for this problem to make it into the modpack

**Comment by thiakil** [comment] 2017-10-03 00:07
> Mekanism's update schedule

I'll see about giving Aidan a poke, as far as I know there isn't a schedule lol
