### ISSUE TITLE
trying to fill immersive Creosote oil in rustics liquid barrel leads to crash and unloadable world

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-3#51] opened 2017-07-16 15:21 UTC
https://pastebin.com/Ku8asqVk
I build u an immersive engineering coke oven and tryed to fill an bucket full of creosote oil in an liquid barrel fom rustic. It crashed to desktop. World cannot be loaded after that. (Restored backup)

**Comment by DietmarKrause** [comment] 2017-07-16 15:24
https://github.com/the-realest-stu/Rustic/issues/56

**Comment by the-realest-stu** [comment] 2017-07-18 03:38
I can't reproduce this on my end, either in a dev environment, or in an ATM3 instance.

That said, the changelog for the most recent IE build (build 0.12-67) says
`- fixed IE's fluids to always stitch into the sheet and have buckets load correctly`,
which would solve the problem, since the null pointer exception in the crash log refers to a line of code that refers only to a TextureAtlasSprite object, meaning that if IE makes it's sprites always load correctly, then the error won't occur.

Essentially, the error is actually on IE's end, and it has apparently been fixed in the latest version of IE, so ATM3 needs to update IE.

**Comment by OrdinatorStouff** [comment] 2017-09-04 21:44
@the-realest-stu thanks for the detailed follow-up

**Closed by OrdinatorStouff** 2017-09-04 21:44 UTC
