### ISSUE TITLE
since 5.2 unplayable on arch linux

### ISSUE THREAD

**Issue by meson11** [AllTheMods/ATM-3#338] opened 2017-12-21 23:26 UTC
since 5.2 atm-3 unplayable (0-1 fps) on arch linux. (singleplayer) 
workaround: install optifine and disable terrain animations

**Comment by coolsa** [comment] 2017-12-22 06:06
This is the same as issue #299 and it was labelled as a "wontfix"

It effects people not just on linux however, as one person there confirmed it was an issue in windows 10.

Its not known how many people this is hitting however. With two reports im guessing its quite a number.

**Comment by OrdinatorStouff** [comment] 2017-12-22 16:41
If someone can assist and see if this is still a problem in 5.6 then I can leave this one open and label as help-wanted and see if someone has time to track down the actual cause (what mod, blocks, system/drivers, etc)

**Comment by meson11** [comment] 2017-12-23 17:31
in 5.6 it is working with terrain animation :-)

**Comment by coolsa** [comment] 2017-12-24 01:05
The issue seems to have been resolved as of 5.6, as im playing on it right now and getting a stable 120 fps. What was changed between this and the version 5.5 that caused this resolution?

**Comment by OrdinatorStouff** [comment] 2017-12-27 22:13
Aside from a few mod updates the only possibly notable change was a Forge downgrade (to fix the oak chest bug).

It looks like someone tried reporting ti to Forge but didn't have enough to make a strong enough argument for discussion:

https://github.com/MinecraftForge/MinecraftForge/issues/4586

http://www.minecraftforge.net/forum/topic/62019-texture-animation-terrain-animations-lag/#comment-291050

Closing this ticket since it's working in 5.6 but we'll try to keep an eye on it

**Closed by OrdinatorStouff** 2017-12-27 22:13 UTC
Labels: annoying, intermittent/hard to track down, mod issue
