### ISSUE TITLE
chisel crash

### ISSUE THREAD

**Issue by electricgamez** [AllTheMods/ATM-3#36] opened 2017-07-13 14:00 UTC
i had made an diamond chisel and wanted to chisel an factory block when i clicked on the chiseld version i wanted it crashed the game

**Comment by TheKrister2** [comment] 2017-07-13 14:12
Posting a crashlog would probably help. This could be because of some convoluted interaction between mods, and it would help the modpack developers to fix it faster as well if they can't recreate it.

**Comment by electricgamez** [comment] 2017-07-13 14:19
[crash-2017-07-13_15.35.49-client.txt](https://github.com/AllTheMods/ATM-3/files/1145472/crash-2017-07-13_15.35.49-client.txt)
ok here it is

**Comment by TheKrister2** [comment] 2017-07-13 14:58
[Crash log for simplicity](https://pastebucket.com/563203) 

If you have it, can you post the full log from that session to pastebin or pastebucket? There might be something in it that can help identify the problem.

I'm not an expert at reading crashlogs, but it seems that something interacted with the GUI and caused the crash. I tried to recreate this by making all the different blocks with the different tiers of chisels, I was unable to cause a crash.

To test this, try disabling your resource pack, if you have any and then try to do the same thing. If it crashes, then the problem is not the resource pack. It is unlikely to be the resource pack, but best to try and be certain.

You can also try to make a new world and test it there. I have encountered bugs that only occur in the world I was playing in.

You can also try to delete the config folder and either let it generate normally or replacing it with a "fresh" atm3 config folder.

**Comment by OrdinatorStouff** [comment] 2017-07-13 16:10
Was fixed in a version that *just missed* making it into this update:
https://minecraft.curseforge.com/projects/chisel/files/2449997

**Comment by DietmarKrause** [comment] 2017-07-13 16:59
same here : https://pastebin.com/837uAUyK
crash when selecting the type of block

**Comment by whatthedrunk** [comment] 2017-07-15 00:45
v2.1 will be up on curse with this fixed. Thanks.

**Closed by whatthedrunk** 2017-07-15 00:45 UTC
