### ISSUE TITLE
Unable to click on arrows or color changer in cart manager gui

### ISSUE THREAD

**Issue by TheElectricCake** [AllTheMods/ATM-3#61] opened 2017-07-19 03:10 UTC
Setting a cart manager block down next to an advanced detector rail, if I open the gui by right-clicking the block, I am able to manually move things in and out of the inventory, but if I click on any of the arrows to change the direction in which the cart manager will interact with carts, or if I click on any of the color-changer icons for any side of the cart manager block, it immediately crashes minecraft out of single-player or SMP.

**Comment by oly2o6** [comment] 2017-07-19 10:23
Known issue with steves carts is clicking buttons in the cart and cart managers, some reason its only affecting some people as a few people on the atm3server are able to do it, guess you could check the steves carts github see if its known, would be appreciated as it will probably get fixed quicker :D

**Comment by OrdinatorStouff** [comment] 2017-09-04 21:55
I was unable to reproduce in latest versions BUT do know that this has been an issue for various players. Due to the age of this issue I'm going to close this one and any new / same issues with StevesCarts can be brought back up

**Closed by OrdinatorStouff** 2017-09-04 21:55 UTC
