### ISSUE TITLE
Demon ingots not melting in smeltry

### ISSUE THREAD

**Issue by Dumpgrah** [AllTheMods/ATM-3#163] opened 2017-09-21 18:28 UTC
when you put demon ingots into the smeltry they do not melt, they start to but give it a min and it will show as not melt able by tinkers smeltry

**Comment by OrdinatorStouff** [comment] 2017-09-21 18:45
duplicate of #109 
Thanks for reporting though, we're still looking into it

**Closed by OrdinatorStouff** 2017-09-21 18:45 UTC
Labels: duplicate
