### ISSUE TITLE
[Minor issue]Bonus Chest wont generate...

### ISSUE THREAD

**Issue by BattleProgramer** [AllTheMods/ATM-3#124] opened 2017-09-10 13:00 UTC
[Minor issue]Bonus Chest wont generate...
When I Create new world...  i usually set bonus chest be Generate.  But it wont generate. thx

version 3.2a

**Comment by TheElectricCake** [comment] 2017-09-12 16:58
Are you making any other changes to worldgen settings? Have you cleared the area to be sure the chest isn't generating but hard to find (common problem). Have you tried creating a superflat to see if the chest does/does not generate there (easier to see things in superflat)?

**Comment by BattleProgramer** [comment] 2017-09-13 16:26
i removed justenoughDimensions, and bonus chest getback

**Comment by OrdinatorStouff** [comment] 2017-09-14 20:22
closing as dupe of #123 -- thanks for the report

**Closed by OrdinatorStouff** 2017-09-14 20:22 UTC
