### ISSUE TITLE
[5.9.2]Cyclic Automated User interaction with empowerer

### ISSUE THREAD

**Issue by galfalek** [AllTheMods/ATM-3#483] opened 2018-04-04 12:32 UTC
So it is a duplication bug that is happening when using the automated user on an empower, with an item in it.
The setup for reprodution.
![2018-04-04_14 23 32](https://user-images.githubusercontent.com/2273236/38307492-341142e2-3814-11e8-8040-3517bf7512e4.png)
![2018-04-04_14 24 41](https://user-images.githubusercontent.com/2273236/38307499-35b2efa6-3814-11e8-8fc7-1d12e9d2133b.png)

It doesnt work with placable items, but can work with ingots, we also duplicate acceleration wands.

Update : i just tried with a stack of item and it duplicate the stack.

**Comment by kjmaster1** [comment] 2018-05-30 23:55
Maybe I have the setup wrong but I was unable to reproduce this - https://streamable.com/gik7f

**Comment by Boomflex** [comment] 2018-05-31 00:03
Issue was fixed in newer version.

Now not applicable.

**Closed by Boomflex** 2018-05-31 00:03 UTC
