### ISSUE TITLE
Extreme reactor carbon plate recipe

### ISSUE THREAD

**Issue by lalleman44** [AllTheMods/ATM-3#256] opened 2017-11-08 10:19 UTC
I can't create carbon fiber for techreborn (recipe does not exist) so extreme reactor casing is a fail :(

![carbon plate fail](https://user-images.githubusercontent.com/33482692/32543821-fa44b320-c476-11e7-8717-236764f8d0c9.jpg)

**Comment by OrdinatorStouff** [comment] 2017-11-08 17:16
The recipe should be oredictionary compatible and I thought there was an IC2 version of the carbon plate that can be used.

**Comment by lalleman44** [comment] 2017-11-08 17:21
thank you for your input :) yes there is a recipe for IC2 but i would like to build without IC2 :)

**Comment by OrdinatorStouff** [comment] 2017-11-08 17:30
Thanks for clarifying -- yes the need for multiple different mods in some modified recipes is intentional. We try to encourage players to use *'all the mods'* for diversity (while trying not to be too annoying if avoidable).

IC2 Machines can be powered by Mek's universal cables (meaning you can use RF for IC2 stuff without transformers) and we turned on the option that lets you break ic2 machines with a pick (instead of needing a wrench all the time) to try to make IC2 more mainstream.

If you still have no interest in touching IC2 at all we offer a "simplified" packmode that disables almost all of our style/thematic custom recipes. This is an all-or-nothing change though, there's no easy way to cherry-pick some recipes over others. If you're interested in this option you can change the `packmode.cfg` setting to "simplified" on your server (if playing SMP) and your client (and if SMP all other clients would also need to make the same change).

Going to close this since it's actually working as intended but if you have other questions of feedback feel free to let us know still.

**Closed by OrdinatorStouff** 2017-11-08 17:30 UTC

**Comment by lalleman44** [comment] 2017-11-08 18:17
thank you so much for your info :) i'm giving IC2 one last change then.
