### ISSUE TITLE
Cobalt ore and Cobalt Block recipe swapped

### ISSUE THREAD

**Issue by Bertieio** [AllTheMods/ATM-3#892] opened 2019-07-25 17:54 UTC
## Expected Behavior
9 Cobalt ingot in a crafting table should make a cobalt block 
1 Cobalt Block in a crafting table should make 9 cobalt ingots

## Current Behavior
9 Cobalt ingot in a crafting table make cobalt ore 
![image](https://user-images.githubusercontent.com/9221294/61896574-33341e00-af0d-11e9-9d22-f2d4ff6daa62.png)
1 Cobalt ore in a crafting table make 9 cobalt ingots
![image](https://user-images.githubusercontent.com/9221294/61896548-20b9e480-af0d-11e9-97e2-3eeb418ae724.png)

## Steps to Reproduce
Place Cobalt ore in crafting table

**Comment by FallenEagle1** [comment] 2019-07-25 18:00
Duplicate of #805

**Closed by FallenEagle1** 2019-07-25 18:00 UTC
Labels: duplicate
