### ISSUE TITLE
Atm3 crash after trying to input item into compacting drawer. (Iron ingot)

### ISSUE THREAD

**Issue by Dviper18** [AllTheMods/ATM-3#895] opened 2019-07-27 12:44 UTC
## Expected Behavior

Put the item in the compacting drawer while not crashing my client.

## Current Behavior

My client crashes and spits out the following log. https://gist.github.com/Dviper18/c30620c2249aa650ed0040f38f3d8088

## Possible Solution

Look into the issue with what is causing this and look for a solution.

## Steps to Reproduce

1. Place compacting drawer down.
2. Take item you want to put into said compacting drawer.
3. Right click with the item in hand.
4. See the magic on how it magically crashes the client.

**Comment by Yamza** [comment] 2019-07-27 12:46
Dupe of https://github.com/AllTheMods/ATM-3/issues/845

**Comment by Darkere** [comment] 2019-07-27 12:46
duplicate of #845

please wait for an update to use the compacting drawer.

**Closed** 2019-07-27 13:14 UTC
Labels: duplicate
