### ISSUE TITLE
Server cashing when starting ATM remix server

### ISSUE THREAD

**Issue by dantheman4700** [AllTheMods/ATM-3#878] opened 2019-06-13 19:09 UTC
Here is the crash report https://gist.github.com/dantheman4700/0de065363ab5596f33efc8505c708d5c
And here is the latest log
https://gist.github.com/dantheman4700/4b3edb11f0ea112640cdf33370b4b1e2

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Yamza** [comment] 2019-06-13 19:12
Disable Nuclearcraft radiation in it's config.

**Comment by dantheman4700** [comment] 2019-06-13 19:23
you are a godsend but do you know why it broke or how to fix it. I really like radiation

**Comment by Yamza** [comment] 2019-06-13 19:25
Because someone is using an rftools filter and the two mods have an issue.
`java.lang.NullPointerException: Exception in server tick loop
	at mcjty.rftools.blocks.itemfilter.ItemFilterTileEntity.getCapability(ItemFilterTileEntity.java:203)
	at nc.util.RadiationHelper.getTileInventory(RadiationHelper.java:60)`

**Comment by turbodiesel4598** [comment] 2019-06-14 05:14
This was fixed on my end, we’re just waiting on an update to the pack to sort this :)
Unfortunately there is still a crash with Minecolonies, but the issue is on their side rather than mine.

**Comment by FallenEagle1** [comment] 2019-08-07 03:51
Modpack update is now live, so should be fixed now

**Closed by FallenEagle1** 2019-08-07 03:51 UTC
