### ISSUE TITLE
Net Recipe

### ISSUE THREAD

**Issue by Bladebearer** [AllTheMods/ATM-3#883] opened 2019-06-23 19:25 UTC
The net recipe for the fisherman strainer, currently isn't working. The recipe calls for 3 string in a line across the center
xxx
sss
xxx

and the result ends up being 2 string back when using the 3 strings.

## Expected Behavior
Net crafted

## Current Behavior
Gives back 2 string instead of the net

## Possible Solution
Not sure which recipe is giving the 2 string, but after removal of that recipe, the net should be craftable. 

## Steps to Reproduce
1. Put 3 string in a crafting table, across the center line horizontally
2. Get 2 string back in recipe

## Detailed Description
As far as I know, there isn't another conflict with this recipe, just the one that takes one string away.

**Comment by FallenEagle1** [comment] 2019-06-23 19:27
Duplicate of #848 already fixed in dev

**Closed by FallenEagle1** 2019-06-23 19:27 UTC

**Comment by Bladebearer** [comment] 2019-06-23 19:39
Oh thank you, sorry. I'll make sure to double check the forum ( found other recipes posts, and missed the net one before posting. Thank you again bud =)


    On Sunday, June 23, 2019, 12:27:22 PM MST, FallenEagle1 <notifications@github.com> wrote:  
 
 
Duplicate of #848 already fixed in dev
