### ISSUE TITLE
Crash on clicking move items button to crafting grid

### ISSUE THREAD

**Issue by madmacf** [AllTheMods/ATM-3#807] opened 2018-11-19 15:29 UTC
Clicking move items button to crafting grid in refined storage. For example planks for chest, the game crashes. It happens every time I do it. First time was trying to make the snow globe from EU2.

Edit: Seem to happen only with some recipies. The planks for the chest and the globe.

I had optifine installed. Removed it. Made no difference.

https://gist.github.com/madmacf/f8dcfe37a022da2c3d351ebf2e63b893

**Comment by Yamza** [comment] 2018-11-19 15:33
Anything wood or saplings likely causes it. Has been an issue for a while.
https://github.com/AllTheMods/ATM3-Remix/issues/82

**Comment by martmists** [comment] 2018-11-19 16:01
closing as duplicate of https://github.com/AllTheMods/ATM3-Remix/issues/82 and cause: Forge/Mod issue.

**Closed by martmists** 2018-11-19 16:01 UTC
